version: "3"
services:
  bitcoinabc-testnet:
    image: uphold/bitcoin-abc:latest
    command: -rpcuser=swapper -rpcpassword=swapper -server=1 -rpcallowip=0.0.0.0/0 -rpcbind=bitcoinabc-testnet -txindex=1 -testnet -rpcport=8332
    volumes:
      - ${BLOCKCHAIN_PATH}/bitcoinabc:/home/bitcoin/.bitcoin
    healthcheck:
      test: ["CMD-SHELL", "curl http://swapper:swapper@bitcoinabc-testnet:8332 -H 'content-type:text/plain;' --data-binary ''"]
      interval: 5s
      timeout: 15s
      retries: 5
    restart: on-failure

  electrumx-testnet:
    image: lukechilds/electrumx
    environment:
      DAEMON_URL: http://swapper:swapper@bitcoinabc-testnet:8332
      COIN: BitcoinCashABC
      PEER_DISCOVERY: "off"
      SERVICES: tcp://:50001
      COST_SOFT_LIMIT: 0 #Disable cost limitation so electrumx does not crash electrum during sync
      COST_HARD_LIMIT: 0
      NET: testnet
    volumes:
      - ${BLOCKCHAIN_PATH}/electrumx:/data
    restart: on-failure

  electron-testnet:
    build: ../../packages/nodechain-electron-cash
    image: electron
    environment:
      NETWORK: ${NETWORK}
      TESTNET: 1
    restart: on-failure

networks:
  default:
    external:
      name: nodechain-network