version: "3"
services:
  ethereumgo-testnet:
    image: ethereum/client-go:stable
    command:
      --http
      --http.addr=ethereumgo-testnet
      --ropsten
      --cache=1024
      --http.port=8545
      --syncmode=snap
      --gcmode=archive
      --ws
      --ws.addr=ethereumgo-testnet
      --ws.port=8546
      --ws.origins=connector
      --http.vhosts=ethereumgo-testnet
      --graphql
      --graphql.vhosts=ethereumgo-testnet
      --override.terminaltotaldifficulty=50000000000000000
    volumes:
      - ${BLOCKCHAIN_PATH}/ethereumgo:/root/.ethereum
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://ethereumgo-testnet:8545"]
      interval: 10s
      timeout: 15s
      retries: 5
    restart: on-failure:5

  beacon-node-testnet:
    build: ../../packages/nodechain-ethereum-consensus
    environment:
      NETWORK: ropsten
      HTTP_WEB3_PROVIDER: /home/ropsten/geth.ipc
      DATA_DIR: /data
      RPC_HOST: beacon-node-testnet
      RPC_PORT: 4000
      GRPC_GATEWAY_HOST: beacon-node-testnet
      GRPC_GATEWAY_PORT: 3500
    volumes:
      - ${BLOCKCHAIN_PATH}/prysm:/data
      - ${BLOCKCHAIN_PATH}/ethereumgo:/home
    depends_on:
      ethereumgo-testnet:
        condition: service_healthy
    restart: on-failure:5

  postgres-testnet:
    build: ../../packages/nodechain-ethereum-indexer
    image: nodechain-ethereum-indexer
    volumes:
      - ${BLOCKCHAIN_PATH}/postgres/testnet:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: swapper
      POSTGRES_PASSWORD: swapper
      POSTGRES_DB: swapper
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres://swapper_writer:swapper_writer@postgres-testnet:5432/swapper"]
      interval: 5s
      timeout: 15s
      retries: 5
    restart: on-failure:5
  
  postgrest-testnet:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgres://swapper_reader:swapper_reader@postgres-testnet:5432/swapper
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: swapper_reader
    depends_on:
      postgres-testnet:
        condition: service_healthy
    restart: on-failure:5

  synchroniser-testnet:
    image: nodechain/eth-transactions-indexer
    environment:
      DB_NAME: postgres://swapper_writer:swapper_writer@postgres-testnet:5432/swapper
      NODE_URL: /home/ropsten/geth.ipc
      START_BLOCK: 0
      CONFIRMATIONS: 0
      PERIOD: 20
    volumes:
      - ${BLOCKCHAIN_PATH}/ethereumgo:/home
    depends_on:
      ethereumgo-testnet:
        condition: service_healthy
      postgres-testnet:
        condition: service_healthy
    restart: on-failure:5

networks:
  default:
    external:
      name: nodechain-network