version: "3"
services:
  terrad-testnet:
    build: ../../packages/nodechain-terrad
    image: terrad
    environment:
      TESTNET: 1
      NET: bombay-12
    volumes:
      - ${BLOCKCHAIN_PATH}/terrad:/root/.terra
    restart: on-failure:5

networks:
  default:
    external:
      name: nodechain-network