version: "3"
services:
  bitcoincore:
    image: uphold/bitcoin-abc:latest
    command: -rpcuser=swapper -rpcpassword=swapper -server=1 -rpcallowip=0.0.0.0/0 -rpcbind=bitcoincore -txindex=1 -rpcport=8332
    volumes:
      - ${BLOCKCHAIN_PATH}/bitcoincode:/home/bitcoin/.bitcoin

  electrumx:
    image: lukechilds/electrumx
    environment:
      DAEMON_URL: http://swapper:swapper@bitcoincore:8332
      COIN: BitcoinCashABC
      PEER_DISCOVERY: "off"
      SERVICES: tcp://:50001
      COST_SOFT_LIMIT: 0 #Disable cost limitation so electrumx does not crash electrum during sync
      COST_HARD_LIMIT: 0
    volumes:
      - ${BLOCKCHAIN_PATH}/electrumx:/data

  electrum:
    build: ../../packages/nodechain-electron-cash
    image: electrum

  connector:
    build: ../../Connector
    environment:
      COIN: BCH
      NETWORK: ${NETWORK}
    image: connector

  nginx:
    image: nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
      - ${CERT_PATH}:/etc/nginx/certs
    ports:
      - ${PORT}:80
      - ${SSL_PORT}:443
