version: "3"
services:
  bitcoincore-mainnet:
    build: ../../packages/nodechain-bitcoin-core
    image: bitcoincore
    command: -rpcuser=swapper
      -rpcpassword=swapper
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=bitcoincore-mainnet
      -txindex=1
      -rpcport=8332
      -zmqpubhashblock=tcp://0.0.0.0:28332
      -rpcthreads=128
    volumes:
      - ${BLOCKCHAIN_PATH}/bitcoincore:/home/bitcoin/.bitcoin
    healthcheck:
      test: ["CMD-SHELL", "curl http://swapper:swapper@bitcoincore-mainnet:8332 -H 'content-type:text/plain;' --data-binary ''"]
      interval: 5s
      timeout: 15s
      retries: 5
    restart: on-failure:5

  electrs-mainnet:
    build: ../../packages/nodechain-electrs
    image: electrs
    command: -v --timestamp
    environment:
      DAEMON_RPC_URL: bitcoincore-mainnet:8332
      ELECTRUM_RPC_URL: electrs-mainnet:50001
    volumes:
      - ${BLOCKCHAIN_PATH}/electrs:/build/.electrs
      - ${BLOCKCHAIN_PATH}/bitcoincore:/home/bitcoin/.bitcoin
    depends_on:
      bitcoincore-mainnet:
        condition: service_healthy
    restart: on-failure:5

networks:
  default:
    external:
      name: nodechain-network