version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
        environment:
          FLASK_CONFIG: develop
          STAGE: development
          PORT: 80
          SSL_PORT: 443
          NGINX_CONFIG_PATH: ../../nginx/nginx.conf
          CERT_PATH: /etc/ssl/certs
          BLOCKCHAIN_PATH: ./blockchain/
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Deploy Development ETH Connector
          command: |
            docker-compose -f docker-compose/development/eth.yml -p eth_development_api up --build -d
      - run:
          name: Run ETH Test
          command: |
            docker exec -it eth_development_api_connector_1 bash -c "cd Connector && python -m pytest -c tests/pytest_eth.ini -s --cov=eth/ --cov=logger/ --cov=rpcutils/ --cov=wsutils/ --cov=. tests/"