version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      STAGE: development
      PORT: 80
      SSL_PORT: 443
      NGINX_CONFIG_PATH: ../../nginx/nginx.conf
      CERT_PATH: /etc/ssl/certs
      BLOCKCHAIN_PATH: ./blockchain/
    steps:
      - checkout
      - run: 
          name: Deploy Development ETH Connector
          command: |
            docker-compose -f Connector/tests/docker-compose/eth.yml -p eth_development_api up --build -d
      - run: 
          name: Allow access to ports
          command: |
            sleep 5 && nc -vz localhost 8545
      - run:
          name: Run ETH Test
          command: |
            docker exec -it eth_development_api_connector_1 bash -c "cd Connector && python -m pytest -c tests/eth/pytest_eth.ini -s --cov=eth/ --cov=logger/ --cov=rpcutils/ --cov=wsutils/ tests/eth"