version: "3"
services:
  bitcoincore-regtest:
    build: ../../packages/nodechain-bitcoin-core
    image: bitcoincore
    command: -rpcuser=swapper
      -rpcpassword=swapper
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -txindex=1
      -prune=0
      -regtest=1
      -debug=1
      -rpcport=8332
      -deprecatedrpc=generate
      -fallbackfee=0.0001
      -zmqpubhashblock=tcp://0.0.0.0:28332
    volumes:
      - ${BLOCKCHAIN_PATH}/bitcoincore:/home/bitcoin/.bitcoin
    healthcheck:
      test: ["CMD-SHELL", "curl http://swapper:swapper@bitcoincore-regtest:8332 -H 'content-type:text/plain;' --data-binary ''"]
      interval: 5s
      timeout: 15s
      retries: 5
    restart: on-failure:5

  electrs-regtest:
    build: ../../packages/nodechain-electrs
    image: electrs
    command: -v --timestamp
    environment:
      REGTEST: 1
      DAEMON_RPC_URL: bitcoincore-regtest:8332
      ELECTRUM_RPC_URL: electrs-regtest:60401
      NETWORK: ${NETWORK}
    volumes:
      - ${BLOCKCHAIN_PATH}/electrs:/build/.electrs
      - ${BLOCKCHAIN_PATH}/bitcoincore:/home/bitcoin/.bitcoin
    depends_on:
      bitcoincore-regtest:
        condition: service_healthy
    restart: on-failure:5

networks:
  default:
    external:
      name: nodechain-network