version: "3"
services:
  ethereumgo-regtest:
    image: ethereum/client-go:latest
    command: --dev --http --http.addr=ethereumgo-regtest --http.api="eth,personal,web3,net,miner" --http.port=8545 --ws --ws.addr=ethereumgo-regtest --ws.port=8546 --ws.origins=connector --http.vhosts=ethereumgo-regtest --graphql --graphql.vhosts=ethereumgo-regtest
    volumes:
      - ${BLOCKCHAIN_PATH}/ethereumgo:/root/.ethereum
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://ethereumgo-regtest:8545"]
      interval: 10s
      timeout: 15s
      retries: 10

  postgres-regtest:
    build: ../../packages/nodechain-ethereum-indexer
    image: nodechain-ethereum-indexer
    volumes:
      - ${BLOCKCHAIN_PATH}/postgres/regtest:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: swapper
      POSTGRES_PASSWORD: swapper
      POSTGRES_DB: swapper
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres://swapper_writer:swapper_writer@postgres-regtest:5432/swapper"]
      interval: 5s
      timeout: 15s
      retries: 5
  
  postgrest-regtest:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgres://swapper_reader:swapper_reader@postgres-regtest:5432/swapper
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: swapper_reader
    depends_on:
      postgres-regtest:
        condition: service_healthy

  synchroniser-regtest:
    image: guenoledc/eth-tx-storage
    environment:
      DB_NAME: postgres://swapper_writer:swapper_writer@postgres-regtest:5432/swapper
      ETH_URL: ws://ethereumgo-regtest:8546
      START_BLOCK: 0
      CONFIRMATIONS_BLOCK: 0
      PERIOD: 20
    depends_on:
      ethereumgo-regtest:
        condition: service_healthy
      postgres-regtest:
        condition: service_healthy

networks:
  default:
    external:
      name: nodechain-network